# GET  http://localhost:5000/admin/get_all_projects
# Content-Type: application/json

# {
    
# }

# GET http://localhost:5000/request/get_all_requests
# Content-Type: application/json

# {
    
# }

# GET http://localhost:5000/request/get_all_requests
# Content-Type: application/json

# {
    
# }

//timesheet fetching by project name
PUT   http://localhost:5000/api/update-project
Content-Type: application/json

{
     "projectId": "67b2e4dc28d7cc5f1379ab4b"
}